name: CI - Lint & Build Check

on:
  push:
    paths:
      - "src/**"
      - "app/**"
      - "components/**"
      - "packages/**"
      - "public/**"
      - "tests/**"
      - "next.config.*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
      - "!ops/**"         # Ops-only Commits ignorieren
  pull_request:
    paths-ignore:
      - "ops/**"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Lint
        run: npm run lint || (echo "::group::lint-log" && npm run lint --silent 2>&1 | tail -n 120 && echo "::endgroup::" && exit 1)
      - name: Build
        env:
          CI: "true"
          NEXT_TELEMETRY_DISABLED: "1"
          NODE_OPTIONS: "--max_old_space_size=4096"
          # Dummy ENVs für Build-Time (keine Secrets nötig)
          NEXT_PUBLIC_SUPABASE_URL: "https://stub.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "stub"
          SITE_URL: "http://localhost:3000"
        run: npm run build